version: '3.8'
services:

  postgres:
    image: postgres:13
    container_name: stunting-postgres 
    restart: always 
    ports:
      - 5432:5432
    env_file:
      - ./backend/.env
    volumes:
      - postgres:/var/lib/postgresql/data
    
  rest: 
    container_name: stunting-rest 
    build:
      context: ./backend
      dockerfile : ./Dockerfile
    ports: 
      - 8080:8080
    env_file:
      - ./backend/.env
    restart: always 
    depends_on:
      postgres:
        condition: service_started
  
  frontend: 
    image: anya-frontend
    container_name : anya-frontend
    build: 
      context: ./frontend
    depends_on : 
      - rest
    ports : 
      - 3000:80
    restart : on-failure

  nginx : 
    image: nginx:mainline-alpine 
    container_name: anya-nginx
    depends_on : 
      - rest 
      - postgres 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

volumes:
  postgres:
    name: stunting-database