item { 
	name:'Ayam_Taliwang'
	id:1
}
item { 
	name:'Beef_Burger'
	id:2
}
item { 
	name:'Beef_Teriyaki'
	id:3
}
item { 
	name:'Chicken_Teriyaki'
	id:4
}
item { 
	name:'Gado_Gado'
	id:5
}
item { 
	name:'Kalio_Ayam'
	id:6
}
item { 
	name:'Karedoks'
	id:7
}
item { 
	name:'Ketoprak'
	id:8
}
item { 
	name:'Martabak_Mesir'
	id:9
}
item { 
	name:'Mi_Aceh_Rebus'
	id:10
}
item { 
	name:'Mie_Ayam'
	id:11
}
item { 
	name:'Mie_Bakso'
	id:12
}
item { 
	name:'Mie_Pangsit_Basah'
	id:13
}
item { 
	name:'Nasi_Gurih'
	id:14
}
item { 
	name:'Nasi_Rames'
	id:15
}
item { 
	name:'Non_Food'
	id:16
}
item { 
	name:'Pempek_Telur'
	id:17
}
item { 
	name:'Rendang_Sapi'
	id:18
}
item { 
	name:'Sop_Daging_Sapi'
	id:19
}
item { 
	name:'Soto_Betawi'
	id:20
}
item { 
	name:'Soto_Padang'
	id:21
}